# Generated by Django 3.2.5 on 2022-05-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cid', models.CharField(max_length=20)),
                ('cname', models.CharField(max_length=20)),
                ('xf', models.CharField(max_length=4)),
                ('address', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=15)),
                ('desc', models.CharField(max_length=50)),
                ('teacher', models.CharField(max_length=20)),
                ('taid', models.CharField(max_length=20)),
                ('xq', models.CharField(max_length=20)),
                ('volumn', models.IntegerField(default=0)),
                ('num', models.IntegerField(default=45)),
            ],
        ),
        migrations.CreateModel(
            name='CourseTemplate',
            fields=[
                ('cid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=20)),
                ('xf', models.CharField(max_length=4)),
                ('xq', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GPA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=8)),
                ('username', models.CharField(default='', max_length=20)),
                ('txf', models.CharField(default='', max_length=8)),
                ('gpa', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cid', models.CharField(max_length=20)),
                ('uid', models.CharField(max_length=8)),
                ('username', models.CharField(default='', max_length=20)),
                ('xq', models.CharField(max_length=20)),
                ('taid', models.CharField(max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('cname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cid', models.CharField(max_length=20)),
                ('cname', models.CharField(max_length=20)),
                ('uid', models.CharField(max_length=8)),
                ('repeat', models.BooleanField(default=False)),
                ('username', models.CharField(default='', max_length=20)),
                ('score', models.IntegerField()),
                ('xf', models.CharField(max_length=4)),
                ('grade', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='sGPA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=8)),
                ('username', models.CharField(default='', max_length=20)),
                ('txf', models.CharField(default='', max_length=8)),
                ('gpa', models.FloatField()),
                ('xq', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='sScore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cid', models.CharField(max_length=20)),
                ('cname', models.CharField(max_length=20)),
                ('uid', models.CharField(max_length=8)),
                ('username', models.CharField(default='', max_length=20)),
                ('score', models.IntegerField()),
                ('taid', models.CharField(max_length=20)),
                ('xf', models.CharField(max_length=4)),
                ('grade', models.FloatField()),
                ('xq', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('identity', models.CharField(max_length=10)),
            ],
        ),
    ]
