# Generated by Django 3.2.5 on 2022-05-20 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sgpa',
            name='txf',
        ),
    ]
