# Generated by Django 3.2.5 on 2022-05-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cname',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='coursetemplate',
            name='cname',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='score',
            name='cname',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='sscore',
            name='cname',
            field=models.CharField(max_length=40),
        ),
    ]
