# Generated by Django 3.2.5 on 2022-05-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS', '0002_remove_sgpa_txf'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='repeat',
            field=models.BooleanField(default=False),
        ),
    ]
