# Generated by Django 3.2.5 on 2022-05-20 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CS', '0003_score_repeat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sGPA',
        ),
    ]
