# Generated by Django 3.2.5 on 2022-05-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CS', '0005_sgpa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sGPA',
        ),
    ]
