# Generated by Django 3.2.5 on 2022-05-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS', '0006_delete_sgpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='sGPA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=8)),
                ('username', models.CharField(default='', max_length=20)),
                ('txf', models.CharField(default='', max_length=8)),
                ('gpa', models.FloatField()),
                ('xq', models.CharField(max_length=20)),
            ],
        ),
    ]
