# Generated by Django 3.2.5 on 2022-02-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS', '0006_auto_20220219_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='volumn',
            field=models.IntegerField(),
        ),
    ]
