# Generated by Django 3.2.5 on 2022-02-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=20)),
                ('xf', models.IntegerField(max_length=1)),
                ('address', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=15)),
                ('desc', models.CharField(max_length=50)),
                ('teacher', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=20)),
                ('uid', models.IntegerField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('identity', models.CharField(max_length=2)),
            ],
        ),
    ]
