# Generated by Django 3.2.5 on 2022-02-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identity',
            field=models.CharField(max_length=10),
        ),
    ]
