# Generated by Django 3.2.5 on 2022-02-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS', '0002_alter_user_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='score',
            field=models.IntegerField(default=0, max_length=3),
        ),
    ]
