# Generated by Django 3.2.5 on 2022-02-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS', '0005_alter_course_xf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='volumn',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='list',
            name='score',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='list',
            name='uid',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
