# Generated by Django 3.2.5 on 2022-02-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS', '0008_list_cname'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tid',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
